### ISSUE TITLE
Deploy onboarding

### ISSUE THREAD

**Issue by pablohoffman** [scrapinghub/shub#126]
It would be nice to add a small wizard when people use `shub deploy` for the first time, to ease the onboarding process. Then, all we need to say in Dash is use `shub deploy` and answer the questions.

```
$ shub deploy
Please login first with: shub login

$ shub login
...

$ shub deploy
Project ID you would like to deploy to: NNNNN
(...maybe validate access to the project? like shub login validates api key...)
Save project ID into scrapinghub.yml [Y/n]?
```

The questions will be asked if no `scrapinghub.yml` is found in the same dir as `scrapy.cfg`.
If you enter `Y` to the last question, the `scrapinghub.yml` file will be created with a default project set to the ID (NNNN) specified and you won't be asked again

**Comment by chekunkov** [comment]
+1 looks like low effort task, I think some users will find that helpful.

+1 to validation
