### ISSUE TITLE
Fail gracefully when API key could not be validated

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#127]
When the [API key validation request](https://github.com/scrapinghub/shub/blob/master/shub/login.py#L55) fails, it throws an unhandled exception and prints a traceback to the command line.

We should catch failed requests and either
1. save the API key without validation, or
2. tell the user that login is not possible right now.

Where I would opt for the first option. However, that request failing means that either the user has no working internet connection or there is a server outage on our side. In both cases, `shub` is pretty much useless (at that moment), so I guess option 2 is viable as well.

On a broader scale, we should introduce a new exception for failed connections with helpful error messages.

**Comment by vshlapakov** [comment]
I don't think it's still actual, if the client can't validate a given API key - it warns about it with a message `API key failed, try again` and asks to repeat again, that should be fine. I'm closing the issue, but feel free to reopen it if I'm missing something.
