### ISSUE TITLE
Avoid dependencies on external tools

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#129]
`shub` opens new Python sessions through the `subprocess` module. In particular, `shub deploy` depends on an available `python` executable (to build an egg through `python setup.py`), and `shub deploy-egg` and `shub deploy-reqs` additionally depend on `pip`.

While PyInstaller does bundle the Python interpreter, it is not an executable file (for Windows builds it bundles `python27.dll` and some additional libraries, which it then loads in the bootloader I guess). I have sent a question (yet to be released by a moderator) to the [PyInstaller mailing list](https://groups.google.com/forum/#!forum/pyinstaller) regarding how to call a new interpreter instance.

For `pip`, for now  we have settled in a Slack dicussion on deactivating the commands when `pip` is not available (for `deploy-egg` we should look into only deactivating the `--from-pypi` switch). There is a mailing list thread on bundling it [here](https://groups.google.com/forum/#!topic/pyinstaller/qZsciPL90c8).

**Comment by pablohoffman** [comment]
I think it's safe to assume the Python interpreter will be available for anyone that wants to do deploys. pip, not so much, so we should handle the case where it may not be available. This is independent of the windows version though.

**Comment by jdemaeyer** [comment]
Hm in that case if we want to be batteries-included we also need to refactor usage of `tar` and `unzip` as these are typically not available on Windows (the standard library has tools for extracting archives).

Do you think getting rid of the dependency to pip should be part of v2?
