### ISSUE TITLE
Don't import non-integer project names

### ISSUE THREAD

**Issue by jdemaeyer** [scrapinghub/shub#149]
`scrapy startproject myprojectname` puts the following section into `scrapy.cfg`:
```ini
[deploy]
project = myprojectname
```

When users first run `shub deploy`, this will be transferred to `scrapinghub.yml` and an error message will be printed.

We should not import non-integer project names from `scrapy.cfg` and instead guide users through the deploy wizard.

**Comment by jdemaeyer** [comment]
This is a big user-friendliness issue. Any user that follows our instructions on the Deploy page will run into an error message instead of into the deploy onboarding wizard.

**Comment by pablohoffman** [comment]
Completely agree @jdemaeyer, can you send a pull request to Scrapy?

**Comment by jdemaeyer** [comment]
Will do. I think this is primarily a `shub` issue though, I'm working on a patch right now and would opt for doing a quick 2.0.2 release when it's merged.
