### ISSUE TITLE
Add `deploy-reqs` session to shub docs

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#152]
deploy-reqs isn't mentioned on the shub docs

http://doc.scrapinghub.com/shub.html

**Comment by jdemaeyer** [comment]
Repeating this here for completeness: This is somewhat on purpose. `deploy-reqs` is very reckless. It re-builds and uploads *all* dependency eggs on *every* invocation, disregarding what libraries are available on SC anyways (http://support.scrapinghub.com/topic/205467-supported-libraries-on-scrapy-cloud/). There are also additonal issues with binaries eggs that have to be built server-side, some of which have been solved in Kumo.

This is definitely far from optimal, but I suggest we wait for Kumo's release and then see how we want to proceed.

See also #56
