### ISSUE TITLE
Allow & character in spider arguments

### ISSUE THREAD

**Issue by mattspaeth** [scrapinghub/shub#176]
I am trying to pass a URL with a '&' character to a spider. Scrapy is removing the & character and everything after it. Unfortunately, this parameter after the '&' is necessary for this page to load. 

http://www.amazon.com/kitchen-dining/b/ref=sd_allcat_ki?ie=UTF8&node=284507

**Comment by jdemaeyer** [comment]
Hey Matt,
`shub` has no issue with forwarding the ampersand, but be aware that `&` is a special character to the shell, separating commands that are to be run simultaneously.

`echo hello&ls` will echo 'hello' and (at the same time) run the command `ls`. Likewise, `shub schedule YourSpider -a yourarg=http://www.amazon.com/kitchen-dining/b/ref=sd_allcat_ki?ie=UTF8&node=284507` will run the shub command up until the `&` and simultaneously try to start the command `node=284507`.

You can either escape the ampersand with a backslash or enclose the argument in quotes. I.e., either of these versions should work for you:
```
shub schedule YourSpider -a yourarg=http://www.amazon.com/kitchen-dining/b/ref=sd_allcat_ki?ie=UTF8\&node=284507
shub schedule YourSpider -a "yourarg=http://www.amazon.com/kitchen-dining/b/ref=sd_allcat_ki?ie=UTF8&node=284507"
shub schedule YourSpider -a yourarg="http://www.amazon.com/kitchen-dining/b/ref=sd_allcat_ki?ie=UTF8&node=284507"
```

Hope this helps :),
-Jakob
