### ISSUE TITLE
Is it time to bump version and push latest code to PyPI?

### ISSUE THREAD

**Issue by chekunkov** [scrapinghub/shub#19]
It looks like in last 2 months shub got several useful features, what about publishing them?

**Comment by pablohoffman** [comment]
+1. who can take care of this?. @chekunkov @josericardo ?

**Comment by eliasdorneles** [comment]
+1 -- I want to start recommending using this in other documentation too.

I can take care of the release (update docs in the repo, bump version and push to PyPI).
If you're okay with it, I'll go ahead with it.

One question: should we try to keep in sync the docs here with the ones in http://doc.scrapinghub.com/shub.html ?
Being the official Scrapinghub docs, that page feels more important than the docs inside the repo, ideally we'd be able to keep them both in sync.

I think I can come up with a hack in the official docs compilation that would download the shub docs from a rst file in this repo -- what do you think?

**Comment by eliasdorneles** [comment]
Btw, what if before the release we add an option `--from-pypi` to `shub deploy-egg` which would download the source from pypi?

`shub deploy-egg --from-pypi python-dateutil` would download the latest sources from pypi to a temp directory, build and upload the egg.

Thoughts?

**Comment by pablohoffman** [comment]
Both suggestions sound good @eliasdorneles, let's do them!

**Comment by josericardo** [comment]
+1 on --from-pypi

**Comment by josericardo** [comment]
--from-pypi PR just made :)

**Comment by eliasdorneles** [comment]
New version released: https://github.com/scrapinghub/shub/releases/tag/v1.3.0
