### ISSUE TITLE
shub deploy fails with no error code

### ISSUE THREAD

**Issue by HosniD** [scrapinghub/shub#197]
shub deploy seems to fail returning the last 30 lines of /tmp/shub_deploy_XXXlog.txt without any error code or description of the fail reason.

The issue in this case came from spider names longer than 60 characters.

**Comment by Gallaecio** [comment]
Is it possible that this issue has been fixed? I’ve just used `shub deploy` to deploy a spider with a 64-characters-long name (`spider_name_that_is_long_enough_to_trigger_shub_issue_number`) and it went fine.

**Comment by Gallaecio** [comment]
I’ve just tried to reproduce the issue deploying a spider with a name that is 64 characters long (`spider_name_that_is_long_enough_to_trigger_shub_issue_number_197`), and it succeeded.

The spider name got truncated to 60 characters, though, so the 60 character limit seems to remain.

Should we consider this issue fixed?

**Comment by vshlapakov** [comment]
@Gallaecio thanks for taking a look, I think we can close this one.
