### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by jamesjackson69** [scrapinghub/shub#224]
I can't run any shub command. Because I get an ImportError

`jjackson2017-mac:~ jjackson2017$ shub login
Traceback (most recent call last):
  File "/usr/local/bin/shub", line 7, in <module>
    from shub.tool import cli
  File "/Library/Python/2.7/site-packages/shub/tool.py", line 7, in <module>
    from shub.utils import update_available
  File "/Library/Python/2.7/site-packages/shub/utils.py", line 14, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: No module named configparser`

I have already done `pip install configparser` and that didn't fix it any other ideas

**Comment by jdemaeyer** [comment]
Hey @jamesjackson69, thanks for raising an issue. Could you try reinstalling `six`:

`pip install -U --force-reinstall six`

I suspect this to be the same as [this issue](http://stackoverflow.com/questions/31662194/python-2-7-no-module-named-configparser).

**Comment by jamesjackson69** [comment]
That worked but I had to use the code below to bypass the error listed [here](http://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11)
`pip install --ignore-installed six`
