### ISSUE TITLE
Deploying spider into the project with existing spiders

### ISSUE THREAD

**Issue by eng1neer** [scrapinghub/shub#230]
When I `shub deploy` a spider to a project that already has other spiders it seems to delete the other spiders. Is there a way to preserve these? Or is there any way to create new projects on scrapinghub via command line interface or API?

**Comment by jdemaeyer** [comment]
Hey @eng1neer, thanks for opening an issue!

Scrapy projects are intended to be concluding in the sense of "all my scraping tools for project XY are in this Scrapy project", and therefore intended to hold multiple related spiders. Scrapy Cloud mirrors this intention and will only ever hold the project that it got from the last `shub deploy`, and never mix spiders from different projects.

There currently is no way to create new Scrapy Cloud projects outside of the web interface, sorry. :<

**Comment by eng1neer** [comment]
Hi @jdemaeyer, thank you for clarifying this. Is there any chance that an API to manage Scrapy Cloud projects will eventually be created?

**Comment by jdemaeyer** [comment]
Hey @eng1neer. We are working on an updated API, but I'm afraid there is currently no concrete plan when it will be released. :/

I'm closing this but will keep monitoring for new comments.
