### ISSUE TITLE
Custom image examples still use list-spiders

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#289]
Hi, I was following the docs and noticed the custom image examples, eg.:

https://github.com/scrapinghub/custom-images-examples/tree/master/examples/python/script

Still use list-spiders.

They should be updated to have a `shub-image-info` command, right? From the docs:

http://shub.readthedocs.io/en/stable/custom-images-contract.html#custom-images-contract

**Comment by jdemaeyer** [comment]
Thanks José! @chekunkov can you create a KUMO issue?

**Comment by chekunkov** [comment]
@jdemaeyer @josericardo created a ticket, thanks

**Comment by chekunkov** [comment]
https://github.com/scrapinghub/custom-images-examples/pull/12

**Comment by jdemaeyer** [comment]
Closed via https://github.com/scrapinghub/custom-images-examples/pull/12
