### ISSUE TITLE
Check for SPIDER_MODULES setting

### ISSUE THREAD

**Issue by lwm** [scrapinghub/shub#293]
In a similar vein to https://github.com/scrapinghub/shub/issues/132, I didn't set the `SPIDER_MODULES` setting and was wondering why my spider never showed up after a `shub deploy`. A warning message would be nice to say that this setting should be present. Will submit a PR if we're all agreed.

**Comment by jdemaeyer** [comment]
Thanks for the issue @lwm 

I don't think this is an issue with `shub` or even Scrapy Cloud. `SPIDER_MODULES` is a mandatory setting in Scrapy projects, and skipping it will also make your spider not show up _locally_:

```
jakob@MosEisley ~/shub/playground % scrapy list
dummy
dummy2
jakob@MosEisley ~/shub/playground %

# After removing the SPIDER_MODULES setting
jakob@MosEisley ~/shub/playground % scrapy list
jakob@MosEisley ~/shub/playground %
```

It will automatically be set with `scrapy startproject`, but if you feel that this is a common stumbling block maybe you can open an issue/PR in [scrapy's repo](https://github.com/scrapy/scrapy/)?

**Comment by lwm** [comment]
Righto @jdemaeyer, I went ahead and followed up with https://github.com/scrapy/scrapy/issues/2846. Perhaps it isn't such a common stumbling block (I didn't know about `startproject`), but let's see what is said in that issue. It's a small issue and can certainly help. Closing :+1:
