### ISSUE TITLE
shub deploy fails ImportError:

### ISSUE THREAD

**Issue by ebrahim-j** [scrapinghub/shub#300]
`ImportError: No module named romanify
 {"message": "shub-image-info exit code: 1", "details": null, "error": "image_info_error"}  
 {"status": "error", "message": "Internal error"}`

**Comment by ebrahim-j** [comment]
Hey, i get this error when I deploy my scraper.. I checked to see and I have the `py-romanify` module installed and in my **requirements.txt**

**Comment by jdemaeyer** [comment]
Hey @ebrahim-j,

thanks for reporting an issue. Did you [tell shub to look for requirements in `requirements.txt`](http://shub.readthedocs.io/en/stable/deploying.html#deploying-dependencies)? I.e. does your `scrapinghub.yml` look something like this?

```
project: YOUR_PROJECT_ID
requirements:
    file: requirements.txt
```

If it does but the deploy still fails, could you paste your `scrapinghub.yml` please?


Cheers!,
-Jakob

**Comment by ebrahim-j** [comment]
Hey @jdemaeyer thanks. That solved it
