### ISSUE TITLE
Deploy projects with pipenv(Pipfile)

### ISSUE THREAD

**Issue by hcoura** [scrapinghub/shub#312]
Since pipenv is the officially recommended Python packaging tool from Python.org. I think we should be able to do `shub deploy...` with a Pipfile rather than a requirements.txt.

**Comment by vshlapakov** [comment]
Makes sense to me, it'd be a nice addition for the tool. 
I won't be able to help with it during next 2 weeks, but PR is welcome :slightly_smiling_face:

**Comment by dyeray** [comment]
I'm taking a look into this. It looks like the logic of shub deploy is divided between image based and old style projects. I think probably those two cases should be managed differently:

1. Check the yaml entry for requirements. If the name is Pipfile.lock use pipenv (soft dependency) to generate a temporary requirements.txt and use it.

2. I'm not sure, but it looks in this case simply the whole directory is uploaded and the Dockerfile of the image is the one in charge of installing the requirements (am I correct?), so adding logic locally to detect whether there is a Pipfile.lock may be a bit dirty, so I'm thinking this case needs to be handled by the image directly. Maybe to offer official support the correct path would be updating the Dockerfile of https://github.com/scrapinghub/scrapinghub-stack-scrapy.

I'm trying to add support for case 1, but the approach can be changed.

**Comment by vshlapakov** [comment]
Thanks for the contribution, I'll release a new version with the changes in the beginning of the next week.
