### ISSUE TITLE
Set global config file path via environment var

### ISSUE THREAD

**Issue by pauloromeira** [scrapinghub/shub#334]
Hi,

I was wondering if it's possible to change this line of code:
https://github.com/scrapinghub/shub/blob/c99943230eefaccabf78a28d443a63dbda067931/shub/config.py#L23

To something like that:
```py
GLOBAL_SCRAPINGHUB_YML_PATH = os.path.expanduser(os.environ.get("SHUB_GLOBAL_CONFIG", "~/.scrapinghub.yml"))
```
To make it possible to specify a custom path to the global config file.

Thanks!

**Comment by vshlapakov** [comment]
Hey, @pauloromeira Thanks for the proposal, addressed with https://github.com/scrapinghub/shub/commit/d7ee8d447942cbbd94bf31092fc88871aaafb3a0.
