### ISSUE TITLE
Document SHUB_APIKEY

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/shub#335]
A customer contacted us after spending some unspecified amount of time trying to get noninteractive deploy working for a CI workflow, and I ended up searching through other projects and then confirming in the shub sourcecode that `SHUB_APIKEY` exists and works.

I think a CI deploy is/should be a best practice since it provides more consistency in the deployed images and can enforce various deploy checks - to that end `SHUB_APIKEY` doesn't seem to be documented anywhere.

**Comment by vshlapakov** [comment]
Addressed by https://github.com/scrapinghub/shub/pull/338, thanks guys @ttilberg @andrewbaxter!
