### ISSUE TITLE
Deploy faild ``Pip checks failed``

### ISSUE THREAD

**Issue by coolmaiev** [scrapinghub/shub#339]
Deploy log last 30 lines:
 ---> 1fdff163774d
Step 10/12 : COPY *.egg /app/
 ---> 1dcf6e56a8d9
Removing intermediate container 629a96828834
Step 11/12 : RUN if [ -d "/app/addons_eggs" ]; then rm -f /app/*.dash-addon.egg; fi
 ---> Running in cea3de4f1a1a
 ---> e68ba40aa058
Removing intermediate container cea3de4f1a1a
Step 12/12 : ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> Running in 48face34e0db
 ---> 920f3cdd1071
Removing intermediate container 48face34e0db
Successfully built 920f3cdd1071
Step 1/3 : FROM alpine:3.5
 ---> 6c6084ed97e5
Step 2/3 : ADD kumo-entrypoint /kumo-entrypoint
 ---> Using cache
 ---> 28a39cd146c9
Step 3/3 : RUN chmod +x /kumo-entrypoint
 ---> Using cache
 ---> 0a0c4ecab5a0
Successfully built 0a0c4ecab5a0
Entrypoint container is created successfully
>>> Checking python dependencies
Requirement already up-to-date: pip==9.0.3 in /usr/local/lib/python3.6/site-packages
hyperlink 18.0.0 has requirement idna>=2.5, but you have idna 2.2.
Warning: Pip checks failed, please fix the conflicts.
{"message": "Dependencies check exit code: 1", "details": "Pip checks failed, please fix the conflicts", "error": "requirements_error"}

**Comment by vshlapakov** [comment]
The error message says that some Python dependencies are not compatible with each other, you should fix it to deploy your project to Scrapy Cloud. Most likely, it's enough to use a newer `idna` version, but if it doesn't help, please contact support.
