### ISSUE TITLE
Cover scrapy-pagestorage in the Custom Images contract documentation

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/shub#343]
Based on the feedback I got in https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/issues/54, I suspect we should extend https://shub.readthedocs.io/en/stable/custom-images-contract.html#custom-images-contract to cover the need to install `scrapy-pagestorage`.

**Comment by vshlapakov** [comment]
Resolved with https://github.com/scrapinghub/shub/pull/345, thanks for the proposal!
