### ISSUE TITLE
Add poetry support

### ISSUE THREAD

**Issue by andrewbaxter** [scrapinghub/shub#347]
[poetry](https://github.com/sdispater/poetry) is another popular (at least, frequently mentioned) python package manager, with a lockfile similar to pipenv's.

**Comment by vshlapakov** [comment]
Thanks for creating it, I'm inclined to add its support. I've been watching for the project development for a few months and it looks pretty promising.

**Comment by andrewbaxter** [comment]
@vshlapakov I'd like to try implementing this.

Poetry 1.0.0 (unreleased) has an "export" command that produces a requirements.txt file.  The code to generate it is pretty clean (`Exporter(locker).export('requirements.txt', cwd, use_hashes=False)`) but it's an undocumented api and does include `-e` lines.  Parsing the lockfile and generating the requirements.txt manually is not too difficult (15-20 lines?) and could be done in a way to mirror the Poetry 1.0.0 code.

Any preference on which approach to take?
