### ISSUE TITLE
'shub login' doesn't work for 'shub deploy'

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#35]
```shub deploy``` only looks for credentials in the project's scrapy.cfg and ~/.scrapy.cfg files.

Does it make sense to make it work with .netrc (shub login) and $SHUB_APIKEY credentials?

**Comment by eliasdorneles** [comment]
yup, the login should work for all commands. is it easy enough to fix that?

**Comment by josericardo** [comment]
yes, I'll add them as fallback credentials for ```deploy``` then :)
