### ISSUE TITLE
Deploy only already-committed stuff

### ISSUE THREAD

**Issue by mredaelli** [scrapinghub/shub#360]
I've been bitten a few times by running `shub deploy` on a git repository where a file was not committed yet (an `__init__.py` in particular), seeing everything fine, then at the next deploy after checking out branches a spider is missing (that file was removed but nobody noticed).

It would be nice to have an option to tell `shub` to deploy not the current status of the filesystem, but the current committed status of the current branch (plus specific ignored files, like `settings`).

Do you think it would make sense?

**Comment by vshlapakov** [comment]
Yeap, there's a similar issue already opened, take a look into https://github.com/scrapinghub/shub/issues/323

**Comment by mredaelli** [comment]
I see. Sorry for the noise :)
