### ISSUE TITLE
shub deploy with pipfile doesn't add sources and fails to deploy from index other than pypi

### ISSUE THREAD

**Issue by DharmeshPandav** [scrapinghub/shub#381]
I was trying to use the pipefile feature to deploy but by SH build was failing with error that package not found
https://shub.readthedocs.io/en/stable/deploying.html#deploying-dependencies

After looking into the code for `shub.deploy`, I found that it loads the package in function 
` _get_pipfile_requirements():`  here: https://github.com/scrapinghub/shub/blob/287138466558cd0255818465a88fd65b71efa9df/shub/deploy.py#L172

This function is loading the `pipfile `and parsing deps before calling  `convert_deps_to_pip(deps)` function from pipenv lib [here](https://github.com/pypa/pipenv/blob/9ab617af77cea7d8c5363ba9d10e5c931440e6ff/pipenv/utils.py#L1426) without the optional project argument

adding sources is required if package is not hosted on pypi  index( i.e. private idnex or other public repo index)

will it be a good idea to 
1. Use/initialize the `Project` object of Pipenv and using available `Pipefile.lock` and accessing  the Project.sources property ( i.e.
 `https://github.com/pypa/pipenv/blob/9ab617af77cea7d8c5363ba9d10e5c931440e6ff/pipenv/project.py#L844) 
2. PR in upstream repo to accept array of indexes ( `_sources` node from `Pipfile.lock`) as optional parameter in `def convert_deps_to_pip(deps, project=None, r=True, include_index=True):` method 
and in `shub.deplyoy` passing `sources` parameter when calling method `convert_deps_to_pip` from `_get_pipfile_requirements`  which is easily accessible when we load deps from `pipfile.lock`

**Comment by DharmeshPandav** [comment]
trying different approach which doesn't require any changes in syntax or upstream package
using `prepare_pip_source_args` and rebuilding  `requirements.txt` file to prepend sources

**Comment by DharmeshPandav** [comment]
what do you think @vshlapakov  ? thanks

**Comment by vshlapakov** [comment]
Sounds like a nice addition to what we have, that's reasonable! The current Pipfile support is very basic, it'd be nice to extend it but having in mind that it's entirely optional, users don't have to install Pipfile to use shub. Reviewed the PR, please take a look :heavy_check_mark:

**Comment by noviluni** [comment]
I think this issue could be closed as this was merged: https://github.com/scrapinghub/shub/pull/382 

@vshlapakov
