### ISSUE TITLE
Incorrect API Key generation URL

### ISSUE THREAD

**Issue by storymode7** [scrapinghub/shub#399]
API key generation URL provided by `shub` : [https://app.scrapinghub.com/account/apikey](https://app.scrapinghub.com/account/apikey)
does not lead to the API Key page. Instead, an error page is shown:
![image](https://user-images.githubusercontent.com/30749042/115999332-ec56e900-a608-11eb-8c18-346d3c57c605.png)

On inspecting with Network Monitor, it's visible that one request raises a 500: Internal Server Error
![image](https://user-images.githubusercontent.com/30749042/115999647-1eb51600-a60a-11eb-885d-e7489ec12b0f.png)

The page works fine when I visit: [https://app.zyte.com/account/apikey](https://app.zyte.com/account/apikey) instead of app.scrapinghub.com

If the change is required in shub, I'll be happy to send a PR.

**Comment by vshlapakov** [comment]
The URL is hard-coded for `shub login` command only, and it still works fine:
```
$ shub login
Enter your API key from https://app.scrapinghub.com/account/apikey
API key: <YOUR-API-KEY>
Validating API key...
API key is OK, you are logged in now.
```
While we do need to update the URL to be consistent, it's definitely not a blocker. You should be logged in at app.zyte.com though, in order to use the URL to access/regenerate your API key - if that's the case, both URLs should point you to the right page. I hope that resolves your issue.

**Comment by storymode7** [comment]
Hi, this appears to be fixed now.
Previously, if I went to the url [app.scrapinghub.com/account/apikey](https://app.scrapinghub.com/account/apikey), then I was redirected to [app.scrapinghub.com/account/login](https://app.scrapinghub.com/account/login) and asked to login again (even if I was logged in at app.zyte.com) and after that the error occurred as shown in the screenshot above.

Now, I'm redirected to [app.zyte.com/account/login](https://app.zyte.com/account/login) immediately.

Sorry for the bother. I'll close this issue now.

**Comment by vshlapakov** [comment]
No worries, thanks for highlighting it. We'll need to update the routes anyway eventually.
