### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by emilbonnek** [scrapinghub/shub#412]
At the moment users will get:
`ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Python310\lib\collections\__init__.py)`

This seems to be because of [this dependency](https://github.com/scrapinghub/python-hubstorage/blob/master/hubstorage/resourcetype.py) (line 4) which needs to be:
`from collections.abc import MutableMapping`

**Comment by dogweather** [comment]
Yep - I just got hit by this.

**Comment by sleao** [comment]
> Yep - I just got hit by this. Is there a workaround?
> 
> I'm thinking I can install an older python with pyenv, and create a virtualenv with it to run the app.

You can just open the file and change the `from collections import MutableMapping` to `from collections.abc import MutableMapping`. It worked for me.
