### ISSUE TITLE
deploy-reqs is not finding some egg versions

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#44]
We have some eggs deployed with ```unknown``` version.

Try:

-e git+https://github.com/scrapinghub/frontera@settings_override#egg=frontera

**Comment by josericardo** [comment]
The version of packages cloned from git is the ```commit-branch``` from the git repository that is cloned by pip. Sometimes pip clones the package and leaves the .git folder, sometimes it doesn't. 

It seems that if the package is already installed, the ```.git``` folder is kept. That's why it seemed to be working fine in the past.

Still not clear how to properly solve this.

**Comment by josericardo** [comment]
One option to solve this is to parse the requirements.txt file and use deploy-egg for each line.

**Comment by bbotella** [comment]
Doesn't seem to be working in every situation. Checking with @josericardo for other approaches.

**Comment by josericardo** [comment]
I think this isn't a problem anymore. The "unknown" in frontera egg was generated by versioneer. I know we had problems with some other eggs, but I can't recall seeing this happen recently.

I'd vote to close this issue.

@eliasdorneles Concerns?
