### ISSUE TITLE
login while already logged-in shows error

### ISSUE THREAD

**Issue by redapple** [scrapinghub/shub#46]
If one is already logged in, `shub login` throws an error, while it could say something less "dramatic"

Current behavior:

```
$ shub login
Usage: shub login [OPTIONS]

Error: Already logged in. To logout use: shub logout
```

- no need to show "Usage" as it's correct
- "Error" is misleading. it could say "You're already logged in. Nothing to do. If you want to login with another API key, use `logout` first", or something along those lines

**Comment by josericardo** [comment]
+1
