### ISSUE TITLE
Crash in deploy-reqs for lxml.

### ISSUE THREAD

**Issue by tmgardner** [scrapinghub/shub#48]
There's a repeatable failure if requirements.txt has lxml in it. When I remove lxml, it builds and deploys the rest of the eggs (which is awesome). Mac Book Pro, OSX Yosemite.

Minimum reproducer:
$ virtualenv --version
13.1.0
$ virtualenv --python=python2.7 venv
Running virtualenv with interpreter ...
Using real prefix '...'
New python executable in venv/bin/python2.7
Also creating executable in venv/bin/python
Installing setuptools, pip, wheel...done.
$ source venv/bin/activate
$ pip install shub
Collecting shub
...
Successfully installed click-4.1 requests-2.7.0 shub-1.3.1 six-1.9.0
$ pip list
click (4.1)
pip (7.1.0)
requests (2.7.0)
setuptools (18.0.1)
shub (1.3.1)
six (1.9.0)
wheel (0.24.0)

$ echo 'lxml==3.4.4' > requirements.txt
$ shub deploy-reqs <my project id> requirements.txt
Downloading eggs...
.../venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
.../venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting lxml==3.4.4 (from -r .../requirements.txt (line 1))
  Using cached lxml-3.4.4.tar.gz
  Saved /var/folders/zw/v2b8vtsj6cn58j55371phlf80000gp/T/eggshv9fpJ/eggs/lxml-3.4.4.tar.gz
Successfully downloaded lxml
Uncompressing: lxml-3.4.4.tar.gz
Building egg in: /private/var/folders/zw/v2b8vtsj6cn58j55371phlf80000gp/T/eggshv9fpJ/eggs/lxml-3.4.4
.../2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
.../2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
.../2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
Traceback (most recent call last):
  File ".../venv/bin/shub", line 11, in <module>
    sys.exit(cli())
  File ".../venv/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File ".../venv/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File ".../venv/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../venv/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../venv/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File ".../venv//lib/python2.7/site-packages/shub/deploy_reqs.py", line 18, in cli
    main(project_id, requirements_file)
  File ".../venv/lib/python2.7/site-packages/shub/deploy_reqs.py", line 27, in main
    utils.build_and_deploy_eggs(project_id, apikey)
  File ".../venv/lib/python2.7/site-packages/shub/utils.py", line 105, in build_and_deploy_eggs
    build_and_deploy_egg(project_id, apikey)
  File ".../venv/lib/python2.7/site-packages/shub/utils.py", line 132, in build_and_deploy_egg
    _deploy_dependency_egg(apikey, project_id)
  File ".../venv/lib/python2.7/site-packages/shub/utils.py", line 138, in _deploy_dependency_egg
    egg_name, egg_path = _get_egg_info(name)
  File ".../venv/lib/python2.7/site-packages/shub/utils.py", line 169, in _get_egg_info
    egg_path = glob(egg_path_glob)[0]
IndexError: list index out of range

**Comment by josericardo** [comment]
Hi @tmgardner, thanks for reporting the issue, we were aware of that. @bbotella will make a PR soon :)

**Comment by josericardo** [comment]
Btw @tmgardner, lxml 3.4.2 is deployed for all projects in the Scrapy Cloud, you don't need to upload it.

**Comment by tmgardner** [comment]
Yeah, I was just using requirements of my dev requirements anyway. I'll use separate requirements files.

**Comment by josericardo** [comment]
I'll reopen it, as the problem will be fixed anyway and other libraries may cause this failure in the future.
