### ISSUE TITLE
deploy-reqs should use the project_id defined in scrapy.cfg

### ISSUE THREAD

**Issue by jmaynier** [scrapinghub/shub#52]
deploy-reqs cli arguments are not consistent with other commands like deploy.
project_id is required but shoud be an optional argument and the command should call the same _get_project function that is defined in deploy.py

**Comment by eliasdorneles** [comment]
Reopening this because it was reverted here: https://github.com/scrapinghub/shub/commit/96ace561973c4996c7753f1c87676e1a1dddc4f2

We need to re-do it in a backward compatible way.

**Comment by jdemaeyer** [comment]
Fixed via #79
