### ISSUE TITLE
Impossible to deploy project on windows platform

### ISSUE THREAD

**Issue by oltarasenko** [scrapinghub/shub#58]
Got an error from user:
![capture](https://cloud.githubusercontent.com/assets/48589/9405443/63aa30e2-4800-11e5-8411-3e978fca56e8.PNG)

The issue was already discussed in another thread. 
http://support.scrapinghub.com/topic/808955-windowserror-32-the-process-cannot-access-the-file/

Suggested fix was: "comment out the temporary file removal in the finally block in deploy.py" needs to be tested on windows platform

**Comment by josericardo** [comment]
The errors on the tmp dir removal are now ignored.
