### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by pablohoffman** [scrapinghub/shub#60]
They're currently failing.

```
$ pytest
[...]
Ran 21 test cases in 8.23s (0.29s CPU), 5 errors, 3 failures, 5 skipped
```

**Comment by josericardo** [comment]
Tests are green again on master

https://travis-ci.org/scrapinghub/shub/builds

**Comment by eliasdorneles** [comment]
It's still failing for me, and the message is suggesting my API key from `~/.scrapy.cfg`.

Also, tests were already green before and the test was failing locally.

We gotta check the isolation of the tests, it is failing or succeeding depending on the environment -- so Travis runs are not very reliable yet.

**Comment by josericardo** [comment]
Travis runs are reliable, our tests coverage is the one to be improved :)
