### ISSUE TITLE
shub deploy could ignore files from .gitignore

### ISSUE THREAD

**Issue by pawelmhm** [scrapinghub/shub#78]
so I have some directories listed in .gitignore e.g. /dev directory where I keep some private dirty dev scripts, I see content of /dev is deployed, I learned this because I have some imports in my dev script, this import is not supported in my deploy target and deploy is failng because of missing import. Is there any way to deploy only actual code and not contents of .gitignore?

**Comment by josericardo** [comment]
hey @pawelmhm, currently you can exclude those via setup.py. shub simply uses it to build the egg and ships it.

**Comment by pawelmhm** [comment]
right sorry forgot about it thanks @josericardo
