### ISSUE TITLE
Let `shub items` outputs in JSON-lines format.

### ISSUE THREAD

**Issue by starrify** [scrapinghub/shub#86]
At this very moment `shub items` outputs results in a format of newline-separated stringified Python `dict`:

```
{u'name': u'item_0', u'foo': u'bar'}
{u'name': u'item_1', u'foo': u'bar'}
```

Personally I think it's better to make it JSON-lines:

```
{"name": "item_0", "foo": "bar"}
{"name": "item_1", "foo": "bar"}
```

Or if we need to keep its backward compatibility, I'd suggest at least we introduce something like `shub items --format=jsonl`.

**Comment by pablohoffman** [comment]
+1  for Json lines. I was expecting it to be like that all along. Please change.
