### ISSUE TITLE
Add `shub update-config` command

### ISSUE THREAD

**Issue by josericardo** [scrapinghub/shub#92]
As we're moving our configuration format to scrapinghub.yml`s, should we make the switch easy by adding a command to generate a config in the new format?

**Comment by pablohoffman** [comment]
I wouldn't bother since there are just a few fields. I would either do nothing or do it automatically (perhaps with a CLI wizard).

**Comment by pablohoffman** [comment]
Since this was a question ticket, I just closed it. Feel free to re-open if you feel strongly about it.
